### ISSUE TITLE
vk2rss.html

### ISSUE THREAD

**Issue by tsarbas** [tsarbas/tsarbas.github.io#1]
vk2rss - читаем стену ВКонтакте в RSS-ленте

**Comment by tsarbas** [comment]
TEST

**Comment by ildar** [comment]
Подскажете, почему https://vk.com/club11004967 не работает? выдаёт пустой фид.

**Comment by tsarbas** [comment]
дело в том что у данной группе не указан короткий адрес, а используется стандартный. Для таких случаев нужно вводить ссылку с id группы... в данном случае ссылка будет выглядеть вот так: https://vk.com/id-11004967. В свой rss reader можете добавить вот эту ссылку: http://vk2rss.sarbas.org/rss/id-11004967

**Comment by ildar** [comment]
Спасибо, помогло! может, это в FAQ?

**Comment by ildar** [comment]
ещё заметил, что <title/> нормально не заполняется. Можно было сразу его
заполнить названием страницы ВК.
-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by ildar** [comment]
Здравствуйте,
похоже, есть ещё одна проблемка.
https://en.wikipedia.org/wiki/RSS#RSS_compared_to_Atom говорит, что для
каждого <item/> должен быть <title/> . Можете исправить?
Заранее спасибо.
P.S. Вылезло вот тут: https://github.com/Etuldan/spaRSS/issues/23

**Comment by tsarbas** [comment]
@ildar, Добавил title item

**Comment by ildar** [comment]
Спасибо! заработало.

**Comment by inkvizitor68sl** [comment]
А ты htaccess и html-ку не хочешь закоммитить ) ?

**Comment by ildar** [comment]
К сожалению, Title item получился только "для галочки". В идеале, конечно,
было бы его заполнить из титула той страницы, которую мы фидим.
Впрочем, и за это спасибо!!!

**Comment by ildar** [comment]
Также хотелось бы иметь возможность "фидить" те странички, которые доступны
пользователям VK.
То есть если в настройках Приватности "Кому в интернете видна *моя
страница" *выставлены в "Только пользователям ВКонтакте"

**Comment by inkvizitor68sl** [comment]
> "Только пользователям ВКонтакте"
+1

А по-хорошему вообще завязаться на токены, чтобы роботным аккаунтом можно было ходить и в закрытые группы (ну или своим в приватной инсталляции).

**Comment by don-rumata** [comment]
А можно инструкцию для тупых, как запустить код на своих мощностях?
